spring:
    datasource:
        url: jdbc:mysql://ecs01:3306/testspringboot?characterEncoding=utf-8
        username: test
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml